### PR TITLE
Upgrade WebDriverIO to v7 and Move to Asynchronous Framework

### PR DESCRIPTION
**Pull request by samuelfreiberg**
### Platforms Impacted
- [ ] iOS
- [X] macOS
- [X] win32 (Office)
- [X] windows
- [ ] android

### Description of changes

WebDriverIO's Synchronous framework is[ now deprecated](https://webdriver.io/docs/sync-vs-async/) due to some breaking changes in Node. We need to move to async. WDIO v7 has some crucial improvements to async that we need as well.

I also made a task to update the E2E Testing docs to include async examples.

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
so many awaits 👀

**Comment by samuelfreiberg** [comment]
> so many awaits 👀

Yup, it's ugly. I'm not sure there's a way around it?

**Comment by samuelfreiberg** [comment]
Temporarily closing. Need to break this down into smaller sections to validate each one working before I get it all working together (mainly updating WDIO to v7 first, validate E2E tests are running, then transform to async)

**Pull request closed without merging**
