### PR TITLE
Flip Shimmer in RTL

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [ ] win32 (Office)
- [ ] windows
- [x] android

### Description of changes

Shimmer didn't flip in RTL, which is pretty bad. We can fix this by adding a G (group) element, and applying a transform to the whole Shimmer in RTL. 

If we like this solution, I'll apply it to other SVG's / components that didn't flip in RTL.

### Verification

Shimmer flips in RTL for macOS. I tested this by running FluentTester with a pseudo right-to-left Language with Xcode.

Screen Shot 2021-12-10 at 1 48 52 PM
                      
Screen Shot 2021-12-10 at 1 48 18 PM

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [x] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Review by chiuam — APPROVED** [review]

**Review by HeyImChris — APPROVED** [review]
Any other controls we need to apply similar logic too?

**Comment by Saadnajmi** [comment]
> Any other controls we need to apply similar logic too?

Any control using an SVG or icon, which includes:
- Icon
- ContextualMenu
- MenuButton

I made this change on Shimmer to see how people felt about my manual SVG transform, and whether it would be a good generic solution. @PPatBoyd specifically wanted input from @warren-ms

**Comment by warren-ms** [comment]
Hi all,
I think this kind of solution is the proper approach to take. SVGs themselves should only be responsible for storing graphic data and provide the standard graphics operations to manipulate them, like doing the mirroring in this case. Determining when the svg should be mirrored, however seems like something that is more overall layout oriented and should be the responsibility of controls that contain svgs as a graphic primitive. They should be the ones that tie into our layout system, detect when RTL mirroring needs to occur and tell the SVG to perform the operation.

In this case the operation to RTL mirror with scale(-1,1) seems correct. I think the <g> might not be necessary in the future though. The SVG2 spec allows for transform to be specified on the SVG element itself. Not sure if liblet_svg supports this at the moment, and the d2d svg support documentation doesn't mention it for d2d.
________________________________

**Comment by Saadnajmi** [comment]
> Hi all,
> I think this kind of solution is the proper approach to take. SVGs themselves should only be responsible for storing graphic data and provide the standard graphics operations to manipulate them, like doing the mirroring in this case. Determining when the svg should be mirrored, however seems like something that is more overall layout oriented and should be the responsibility of controls that contain svgs as a graphic primitive. They should be the ones that tie into our layout system, detect when RTL mirroring needs to occur and tell the SVG to perform the operation.
> 
> In this case the operation to RTL mirror with scale(-1,1) seems correct. I think the <g> might not be necessary in the future though. The SVG2 spec allows for transform to be specified on the SVG element itself. Not sure if liblet_svg supports this at the moment, and the d2d svg support documentation doesn't mention it for d2d.
> ________________________________
> From: Saad Najmi ***@***.***>
> Sent: Tuesday, December 14, 2021 11:38 AM
> To: microsoft/fluentui-react-native ***@***.***>
> Cc: Warren Leung[He/Him] ***@***.***>; Mention ***@***.***>
> Subject: Re: [microsoft/fluentui-react-native] Flip Shimmer in RTL (PR #1239)
> 
> 
> Any other controls we need to apply similar logic too?
> 
> Any control using an SVG or icon, which includes:
> 
>   *   Icon
>   *   ContextualMenu
>   *   MenuButton
> 
> I made this change on Shimmer to see how people felt about my manual SVG transform, and whether it would be a good generic solution. @PPatBoyd<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPPatBoyd&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pXl627fufdU3UC0dPsrLSmNXMYCCghsBM4fY%2FOGPc2E%3D&reserved=0> specifically wanted input from @warren-ms<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwarren-ms&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E7%2FhDsEf%2F519ObegpsZywDWqEqPMkwPNL0Bc7U16khA%3D&reserved=0>
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffluentui-react-native%2Fpull%2F1239%23issuecomment-993917380&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oX9gxgAg2iTqWHQMLYfJDUcW%2Bo%2FulRsh7fGUqgXynPo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPCVKIRMXXMCB36OALZADNTUQ6MM7ANCNFSM5J2LQ2KQ&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hnJggG5jBWGcwQ%2FcGwGgBgXOdAtj0TklXI%2BQNpIw0s4%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nO2z9tjSUO39Y2dp4H%2FUx%2Bz0woUziKn8E6yFNsttpL0%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CWarren.Leung%40microsoft.com%7C78eb0d8d9e06405a88b108d9bf395de0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637751075458015164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1CZQC48UkdwMTudjSpPoMWO5tuISaUx0uAk0A1OjSGA%3D&reserved=0>.
> 

I don't think react-native-svg supports SVG2, as I tried putting the transform directly on <SVG> as well. Good to know though!

**Pull request merged**
