### PR TITLE
Fixes Experimental Expanders WinUI Dependency

### PR DESCRIPTION
**Pull request by TatianaKapos**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [x] win32 (Office)
- [x]  windows
- [ ] android

### Description of changes

Fixes Experimental Expanders WinUI dependency that breaks on RNW .67
Resolves https://github.com/microsoft/react-native-gallery/issues/183

### Verification
Tested locally, no tests currently for experimental expander

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Review by HeyImChris — APPROVED** [review]

**Comment by rurikoaraki** [comment]
@TatianaKapos please run `yarn change` and push the commit it generates to allow the PR build to pass. Thanks!

**Comment by TatianaKapos** [comment]
@Saadnajmi Sorry for the late reply, took some time to look into the example app and get it running for windows!

But Expander already depended on WinUI 2.6, this change makes it so ExperimentalFeatures.props can decide which versions of the Windows SDK and WinUI 2.x to use. Interestingly this doesn't help the example app as I expected it to do, the error might not depend on versioning

**Comment by rurikoaraki** [comment]
@Saadnajmi are we okay with merging this?

**Comment by Saadnajmi** [comment]
> @Saadnajmi are we okay with merging this?

Yeah, I'm not sure if we ever got Expander working inside FURN itself. I think it had to be used in a standalone test app. So any improvement to the control is fine to me =)

**Pull request merged**
