### PR TITLE
Add explicit react-native-svg dependency to FURN Icon

### PR DESCRIPTION
**Pull request by amgleitman**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Specify an explicit dependency on react-native-svg for FURN Icon.

### Verification

Verified that the test app still runs without any issues.

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Can you add it to `apps/ios` and `apps/macos` too? I think we added it to `apps/FluentTester` (which iOS and macOS depend on) but I found out the react native CLI doesn't support transitive dependencies on purpose (https://github.com/react-native-community/cli/issues/923)

**Comment by Saadnajmi** [comment]
Looks like we can close this because https://github.com/microsoft/fluentui-react-native/pull/668 took care of it

**Comment by amgleitman** [comment]
> Looks like we can close this because #668 took care of it?

I think we still need the change in `packages/experimental/Icon/package.json`.

**Comment by Saadnajmi** [comment]
> > Looks like we can close this because #668 took care of it?
> 
> I think we still need the change in `packages/experimental/Icon/package.json`.

Yep, sorry my bad. I missed that in the other PR

**Review by Saadnajmi — APPROVED** [review]

**Review by HeyImChris — APPROVED** [review]

**Pull request merged**
