### PR TITLE
Fluent Tester: App Icons + iPad multitasking support + app icons

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [ ] win32 (Office)
- [ ] windows
- [x] android

### Description of changes

Let's bump us to the latest release of react-native-test-app, which gets us a lot of goodies :) 

1) Turbomodule support. https://github.com/microsoft/react-native-test-app/pull/843
2) App icon support. https://github.com/microsoft/react-native-test-app/pull/1022
3) iPad Slide Over window / multi-tasking support. https://github.com/microsoft/react-native-test-app/pull/1032

We also got a designer to make us icons =). I chose the blue set over the pink set.

### Verification

I didn't test building with turbo modules, we don't quite support this yet anyway. 

Verified that SlideOver windows work on iOS. Some additional JS fixes are needed to make layout act properly though.

Android icon:
Screen Shot 2022-08-03 at 11 54 53 AM

macOS icon (dock):
image

iOS icon
Screen Shot 2022-08-03 at 10 45 12 AM

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by harrieshin** [comment]
no podlock changes for macOS?

**Review by harrieshin — APPROVED** [review]

**Review by chiuam — APPROVED** [review]

**Comment by Saadnajmi** [comment]
macOS test app seems broken. Investigating.

**Review by mischreiber — APPROVED** [review]

**Comment by Saadnajmi** [comment]
Indeed, the addition of macOS E2E testing found a bug in react-native-test-app for macOS, which is why our CI is failing. Opened an issue here: https://github.com/microsoft/react-native-test-app/issues/1039

Thanks @samuelfreiberg :)

**Comment by ValentinaKozlova** [comment]
Nice icons! I like the color :)

**Pull request merged**
