### PR TITLE
Update Fluent Tester readme

### PR DESCRIPTION
**Pull request by ejlayne**
Edit Fluent Tester instructions for running on Win32, per Nikolai's issue. https://github.com/microsoft/fluentui-react-native/issues/194

### CODE REVIEW

**Comment by FalseLobster** [comment]
You know, I just realized these instructions are inaccurate for Windows.  Maybe this should be in the win32 specific subdir for now?

**Comment by ejlayne** [comment]
It would make sense to add instructions for each platform if they are different, and then just have this readme link off to the platform specific instructions. @FalseLobster any objections?

**Comment by FalseLobster** [comment]
> It would make sense to add instructions for each platform if they are different, and then just have this readme link off to the platform specific instructions. @FalseLobster any objections?

No objections here.  This readme.md is already replicated in the win32 directory, so maybe make this change over there and link from here to there?

**Comment by ejlayne** [comment]
Closing this PR - will open separate PR for the right set of changes.

**Pull request closed without merging**
