### PR TITLE
Bump react-native-test-app version

### PR DESCRIPTION
**Pull request by JasonVMo**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

This is a test-only change to bump the version of react-native-test-app to the latest version. This is being done in preparation for converting the react-native-windows version to use react-native-test-app. The update is needed because only the more recent versions include the nuget support (so we don't have to build everything from source).

### Verification

Currently the verification is simply running it through the automated tests. I'll try to do some manual testing as well but wanted to kick the tests.

### Pull request checklist

This PR has considered (when applicable):
- [x] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Last time I tried this, it broke the android test app for whatever reason. Also, if we're doing this to prep for moving react-native-windows, I can probably close this PR (https://github.com/microsoft/fluentui-react-native/pull/552) ?
I had windows working with react-native-tet-app but it failed our CI :(

**Comment by Saadnajmi** [comment]
@arazabishov @mnkshukl Any idea why the Android CI is failing? Looks like we're just missing a field in the build.gradle for `compileSDKversion`?

**Review by HeyImChris — APPROVED** [review]

**Comment by tamasane** [comment]
> @arazabishov @mnkshukl Any idea why the Android CI is failing? Looks like we're just missing a field in the build.gradle for `compileSDKversion`?
I tried bumping rnta locally and found that `apps\android\src\build.gradle` requires changes. The `buildscript` block needs to be updated. Tested and working. The new `build.gradle` looks as follows:

```
buildscript { scriptHandler ->
    def androidTestAppDir = "../../../node_modules/react-native-test-app/android"
    apply from: "$androidTestAppDir/dependencies.gradle"
    apply from: "$androidTestAppDir/force-resolve-trove4j.gradle", to: scriptHandler

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$androidPluginVersion"
    }
}
allprojects {
    repositories {
        maven {
            // All of React Native (JS, Android binaries) is installed from npm
            url "$rootDir/../../../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../../../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
    }
}
```

**Comment by arazabishov** [comment]
@tamasane solution is correct. I've prepared a fix for RNTA that automatically links `dependencies.gradle` and `force-resolve-trove4j.gradle`, so then library consumers don't have to do it. If you want to, you can re-use `dependencies.gradle` for `androidPluginVersion` variable, but it will be completely optional once the PR is merged.

**Comment by Saadnajmi** [comment]
> @tamasane solution is correct. I've prepared a fix for RNTA that automatically links `dependencies.gradle` and `force-resolve-trove4j.gradle`, so then library consumers don't have to do it. If you want to, you can re-use `dependencies.gradle` for `androidPluginVersion` variable, but it will be completely optional once the PR is merged.

Thanks to both of you! I would personally prefer waiting for the new version and having RNTA link it for us automatically. Appreciate the quick fix!

**Comment by arazabishov** [comment]
The fixed version is released now (v0.5.6). Thanks to @tido64 for a quick code review.

**Review by Saadnajmi — APPROVED** [review]

**Comment by tido64** [comment]
@ArazAbishov Do you know why the CI is failing on this? Shouldn't we be using 1.4?

```
> Task :app:compileDebugKotlin FAILED
e: /Users/runner/work/1/s/node_modules/react-native-test-app/android/app/src/main/java/com/microsoft/reacttestapp/TestApp.kt: (40, 14): The feature "trailing commas" is only available since language version 1.4
```

**Comment by arazabishov** [comment]
@tido64 RNTA follows the kotlin version specified by the project root. For this project, it is set to 1.3.72 at `fluentui-react-native/apps/android/src/build.gradle`:

```groovy
buildscript { 
    ext.kotlin_version = "1.3.72"    
}
```

I would recommend bumping the Kotlin version. Alternatively, we can patch RNTA to avoid using features from 1.4+.

**Comment by Saadnajmi** [comment]
Any update on this / chance we can get it merged @JasonVMo ? We have some people looking into contributing UWP native modules and I was hoping that this PR would fix #552 and let us use RNTA for the windows test app.

**Comment by tido64** [comment]
I have draft PR that touches the same files: https://github.com/microsoft/fluentui-react-native/pull/744

**Comment by tido64** [comment]
Superseded by  #744

**Pull request closed without merging**
