### PR TITLE
E2E tests for V1 Button

### PR DESCRIPTION
**Pull request by rurikoaraki**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Adding E2E tests & E2E automation test for the V1 Button. The structure is copied from the existing Button component.

### Verification

I'm having trouble running these locally so I'm hoping the CI can validate that they're running properly for me.

### Pull request checklist

This PR has considered (when applicable):
- [x] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by chiuam** [comment]
I don't think E2E tests are added for mac yet, will this be blocking V1 completion?

**Comment by rurikoaraki** [comment]
> I don't think E2E tests are added for mac yet, will this be blocking V1 completion?

We would like to have them in place, but if there's a blocker like that I think we can move forward without it for Mac, as long as other tests are in place. For JS based components, hopefully having E2E tests running on one platform provides at least partial coverage for other platforms.

Do you know how long it would take for E2E tests to be stood up in Mac?

**Comment by Saadnajmi** [comment]
> > I don't think E2E tests are added for mac yet, will this be blocking V1 completion?
> 
> We would like to have them in place, but if there's a blocker like that I think we can move forward without it for Mac, as long as other tests are in place. For JS based components, hopefully having E2E tests running on one platform provides at least partial coverage for other platforms.
> 
> Do you know how long it would take for E2E tests to be stood up in Mac?



> > I don't think E2E tests are added for mac yet, will this be blocking V1 completion?
> 
> We would like to have them in place, but if there's a blocker like that I think we can move forward without it for Mac, as long as other tests are in place. For JS based components, hopefully having E2E tests running on one platform provides at least partial coverage for other platforms.
> 
> Do you know how long it would take for E2E tests to be stood up in Mac?

The last I heard, @samuelfreiberg was working on that.

**Comment by samuelfreiberg** [comment]
Tracking integrating E2E testing for Mac with this task: https://office.visualstudio.com/OC/_workitems/edit/5330563

Goal is to be done next week!

**Review by samuelfreiberg — APPROVED** [review]

**Review by ValentinaKozlova — APPROVED** [review]

**Pull request merged**
