### PR TITLE
typo in documentation

### PR DESCRIPTION
**Pull request by ejlayne**
updated typo in documentation to correctly point to /themed-settings/README.md

### CODE REVIEW

**Comment by ejlayne** [comment]
@HeyImChris it looks like the Apple PR failed on this, where I just changed a readme file. The check that failed on this one looked like it passed on my other PR that I submitted about an hour before this one: https://github.com/microsoft/fluentui-react-native/pull/188. Can you please investigate?

**Comment by anandrajeswaran** [comment]
@ejlayne @HeyImChris From the logs:
Found changes in the following packages: 
  @uifabricshared/foundation-compose
Run 'yarn change' to generate a change file
ERROR: Change files are needed!
error Command failed with exit code 1.

**Comment by HeyImChris** [comment]
> @HeyImChris it looks like the Apple PR failed on this, where I just changed a readme file. The check that failed on this one looked like it passed on my other PR that I submitted about an hour before this one: #188. Can you please investigate?

Run `yarn` from root and see if a yarn.lock file is requested to get added

> @HeyImChris it looks like the Apple PR failed on this, where I just changed a readme file. The check that failed on this one looked like it passed on my other PR that I submitted about an hour before this one: #188. Can you please investigate?

Try running `yarn` from root

**Comment by HeyImChris** [comment]
> > @HeyImChris it looks like the Apple PR failed on this, where I just changed a readme file. The check that failed on this one looked like it passed on my other PR that I submitted about an hour before this one: #188. Can you please investigate?
> 
> Run `yarn` from root and see if a yarn.lock file is requested to get added

Should be working now. It needed a change file which I pushed up. The CI got past the part it broke on before

**Pull request merged**
