### PR TITLE
Fix pipeline more

### PR DESCRIPTION
**Pull request by rurikoaraki**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Missed a package, oops. Fixing interactive-hooks, too.

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Comment by ksiler** [comment]
Could you add 

```
{
      "pattern": "https://cla.opensource.microsoft.com"
}
```

to the ignoredPatterns list in `markdown-link-check-config.json`? The link https://cla.opensource.microsoft.com does not work but I assume it will be fixed soon and this will unblock PRs for now.

**Comment by Saadnajmi** [comment]
> "pattern": "https://cla.opensource.microsoft.com"

I ended up including that in #2259 since I'm also trying to merge that today. I guess it's whoever merges first.

**Comment by rurikoaraki** [comment]
> > "pattern": "https://cla.opensource.microsoft.com"
> 
> I ended up including that in #2259 since I'm also trying to merge that today. I guess it's whoever merges first.

I'll let you merge that, since if I start a build now it'll probably end up being slower than your PR.

**Comment by Saadnajmi** [comment]
> > > "pattern": "https://cla.opensource.microsoft.com"
> > 
> > 
> > I ended up including that in #2259 since I'm also trying to merge that today. I guess it's whoever merges first.
> 
> I'll let you merge that, since if I start a build now it'll probably end up being slower than your PR.

Merged and re-ran the check on this PR

**Pull request merged**
