### PR TITLE
Bug fix - Bump android design tokens

### PR DESCRIPTION
**Pull request by ankraj12**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [x] android

### Description of changes

Integrated a new version for tokens with updated color values.
### Verification

Manually tested.

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Review by lyzhan7 — APPROVED** [review]
Looks like there were some visual changes to Switch since the snapshot got updated - do you have before/after screenshots?

**Comment by rohanprasadofficial** [comment]
@lyzhan7 , as far as i know , we have wrong token values on Switch tokens , now it have been fixed , maybe that's why the snapshots got updated.

**Comment by ankraj12** [comment]
> Looks like there were some visual changes to Switch since the snapshot got updated - do you have before/after screenshots?

It was a swap of light and dark colors used in switch that caused the screenshots updated.

**Comment by lyzhan7** [comment]
Yep I understand that the colors before were incorrect so jest snapshots getting updated in this change is expected. However whenever there's a visual change (including when the previous state was incorrect) it's still good practice to add screenshots of what the tester looks like before and after to ensure that the "after" state is actually correct. Adding screenshots to PRs when something visual changes can also be useful when trying to debug a regression

**Pull request merged**
