### PR TITLE
Update react-native-test-app to 0.2.1, Add Android test app

### LINKED ISSUE #427: Hook up react-test-app for android
#### Platform
- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [x] android
 
#### Describe the feature that you would like added

Right now it is too hard to test android versions of the components. To achieve this the test app from the Oslo team needs to be integrated into the repo.

#### What component or utility would this be added to

Likely apps/android would be the location for it in the repo.

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [ ] win32
- [ ] windows
- [x] android

### Description of changes

The latest version of react-native-test-app fixes a bug that allows us to use the Android test app as well. Let's add it, and update the macOS/iOS versions while we're at it. This closes #427 

### Verification

Ran all three test apps.
To run android, we must run `open -a "Android Studio" .` from `apps/android` to generate the android project. From there, we can launch and run from Android Studio. I still had to manually start the dev packager, unlike the apple platform test apps.

Screen Shot 2020-09-08 at 7 35 25 AM

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
@tido64 I think the main difference I had creating the test app from the instructions on your wiki was that I needed to keep a local copy the build.gradle file to generate the test app, where that was not explicitly listed as required for react-native-test-app to function.

**Comment by tido64** [comment]
> @tido64 I think the main difference I had creating the test app from the instructions on your wiki was that I needed to keep a local copy the build.gradle file to generate the test app, where that was not explicitly listed as required for react-native-test-app to function.

That's odd. If you look at the Example app, [`build.gradle` is empty](https://github.com/microsoft/react-native-test-app/blob/master/example/android/build.gradle). Originally, we didn't have the file at all but Android Studio generated it every time the app got built so we checked it in. Have you tried emptying the file, then restart Android Studio, clear build cache, and rebuild? @arazabishov might have more insight here...

**Comment by Saadnajmi** [comment]
@tido64 I initially needed it to have the proper path to node_modules bc monorepo. Now that we have a working test app though, I'll see if I can delete it and we still generate the right test aoo

Inside build.gradle, I needed to add the extra ../ to get that to work
` url("$rootDir/../../node_modules/jsc-android/dist")`

**Comment by tido64** [comment]
> @tido64 I initially needed it to have the proper path to node_modules bc monorepo. Now that we have a working test app though, I'll see if I can delete it and we still generate the right test aoo
> 
> Inside build.gradle, I needed to add the extra ../ to get that to work
> ` url("$rootDir/../../node_modules/jsc-android/dist")`

I cleared out `build.gradle` on this branch, cleared out the Android Studio cache, and everything works as expected. Most of the magic happens inside `/apps/android/settings.gradle`, so you shouldn't need `build.gradle` at all.

**Comment by Saadnajmi** [comment]
@tido64 You are correct. I think I might have just had an error from back when we were using the wrong version of hermes. I've emptied out the build.gradle file now.

**Review by tido64 — APPROVED** [review]

**Review by arazabishov — APPROVED** [review]

**Review by JasonVMo — APPROVED** [review]
Thanks for doing this, looks good to me.

**Pull request merged**
