### PR TITLE
Move CI to use Xcode 13.1

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Simple bump to use Xcode 13.1 for our CI / Publish pipelines

### Verification

Automated CI should be enough. 

### Pull request checklist

This PR has considered (when applicable):
- [x] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
So far 2 of 3 runs have had run-ios pass. I'm blindly hoping that the Xcode 13 bump makes that check a little more stable, but it seems we should probably file a bug with Azure Pipelines about it still.

**Review by mischreiber — APPROVED** [review]

**Comment by Saadnajmi** [comment]
Currently, This change makes the iOS PR job fail much more frequently (only 1 of 5 runs passed). I'll see if I can fix that or file a bug on Azure Pipelines, because it looks like it's just that some machines aren't provisioned with a simulator to run iOS apps or something like that.

Will hold off on merging till that's resolved.

**Pull request merged**
