### PR TITLE
Focus first element on popover open

### PR DESCRIPTION
**Pull request by rurikoaraki**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Focus should move to the first element when the popover appears.
Easy fix, need to add "setInitialFocus" to the wrapped Callout

### Verification

focus

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
This is unfortunately one of the quirks the macOS Callout doesn't do well. I had to basically hardcode the behavior in ContextualMenu:  https://github.com/microsoft/fluentui-react-native/blob/36ea0d81629f9326eb8c23912d9949381014dade/packages/components/ContextualMenu/src/ContextualMenu.tsx#L44 . Probably should have an action item on me to investigate/fix that.

Related: Is there not a `shouldFocusOnMount` prop equivalent in V1 menu? In the old ContextualMenu, it was programmatic whether you placed focus when the Callout was shown, and `shouldFocusOnContainer` determined if we focus on the first menu item, or the containing view instead. I guess we just got rid of both of those levels of control? (fine by me, though macOS and win32 differ slightly in expectations)

**Review by Saadnajmi — APPROVED** [review]
Regardless of the quirks I mentioned, this change should be fine

**Comment by rurikoaraki** [comment]
> This is unfortunately one of the quirks the macOS Callout doesn't do well. I had to basically hardcode the behavior in ContextualMenu:
> 
> https://github.com/microsoft/fluentui-react-native/blob/36ea0d81629f9326eb8c23912d9949381014dade/packages/components/ContextualMenu/src/ContextualMenu.tsx#L44
> 
> . Probably should have an action item on me to investigate/fix that.
> Related: Is there not a `shouldFocusOnMount` prop equivalent in V1 menu? In the old ContextualMenu, it was programmatic whether you placed focus when the Callout was shown, and `shouldFocusOnContainer` determined if we focus on the first menu item, or the containing view instead. I guess we just got rid of both of those levels of control? (fine by me, though macOS and win32 differ slightly in expectations)

Oh interesting, didn't know about the differences here. I can expose `shouldFocusOnMount` as a prop for V1 Menu and add some default behavior per platform? The Menu spec does call out that these props are not on the Menu anymore, but we can change that if there are platform expectations.

**Comment by Saadnajmi** [comment]
> > This is unfortunately one of the quirks the macOS Callout doesn't do well. I had to basically hardcode the behavior in ContextualMenu:
> > https://github.com/microsoft/fluentui-react-native/blob/36ea0d81629f9326eb8c23912d9949381014dade/packages/components/ContextualMenu/src/ContextualMenu.tsx#L44
> > 
> > . Probably should have an action item on me to investigate/fix that.
> > Related: Is there not a `shouldFocusOnMount` prop equivalent in V1 menu? In the old ContextualMenu, it was programmatic whether you placed focus when the Callout was shown, and `shouldFocusOnContainer` determined if we focus on the first menu item, or the containing view instead. I guess we just got rid of both of those levels of control? (fine by me, though macOS and win32 differ slightly in expectations)
> 
> @Saadnajmi Oh interesting, didn't know about the differences here. I can expose `shouldFocusOnMount` as a prop for V1 Menu and add some default behavior per platform? The Menu spec does call out that these props are not on the Menu anymore, but we can change that if there are platform expectations.

I would keep it out for now. I don't want to expose those props if we get rid of them :P. We can instead just have custom code per platform to do what we need. We can talk more offline about this too if need be, I think I might have some assumptions that are wrong

**Comment by rurikoaraki** [comment]
> > > This is unfortunately one of the quirks the macOS Callout doesn't do well. I had to basically hardcode the behavior in ContextualMenu:
> > > https://github.com/microsoft/fluentui-react-native/blob/36ea0d81629f9326eb8c23912d9949381014dade/packages/components/ContextualMenu/src/ContextualMenu.tsx#L44
> > > 
> > > . Probably should have an action item on me to investigate/fix that.
> > > Related: Is there not a `shouldFocusOnMount` prop equivalent in V1 menu? In the old ContextualMenu, it was programmatic whether you placed focus when the Callout was shown, and `shouldFocusOnContainer` determined if we focus on the first menu item, or the containing view instead. I guess we just got rid of both of those levels of control? (fine by me, though macOS and win32 differ slightly in expectations)
> > 
> > 
> > @Saadnajmi
> >             
> >             Saad Najmi
> >             FTE Oh interesting, didn't know about the differences here. I can expose `shouldFocusOnMount` as a prop for V1 Menu and add some default behavior per platform? The Menu spec does call out that these props are not on the Menu anymore, but we can change that if there are platform expectations.
> 
> I would keep it out for now. I don't want to expose those props if we get rid of them :P. We can instead just have custom code per platform to do what we need. We can talk more offline about this too if need be, I think I might have some assumptions that are wrong

@SaadNajmi done with latest commit.

**Pull request merged**
