### PR TITLE
[Callout] Fix callout reanchoring from `target` to `anchorRect`

### PR DESCRIPTION
**Pull request by nakambo**
### Platforms Impacted
- [ ] iOS
- [x] macOS
- [x] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

The callout doesn't reanchor when it has rendered with a `target` anchor and new props specify `anchorRect`. It would seem native code never gets an update that `target` isn't specified anymore, because we don't update internal state used to populate that prop -- so fixing that.

Also making changes to the test page to validate the dynamic changing of anchor.

### Verification

Manually, using the updated test page. New behavior video: https://github.com/microsoft/fluentui-react-native/assets/72474613/d64107b7-caa3-4301-81bc-3f9b50d87a74

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Can you attach a video of the new behavior as well? Thank you for the change!

**Review by Saadnajmi — APPROVED** [review]

**Comment by nakambo** [comment]
> Can you attach a video of the new behavior as well? Thank you for the change!

attached

**Comment by Saadnajmi** [comment]
An FYI, on macOS I get a crash when I try to change anchors with the new button..

**Review by PPatBoyd — APPROVED** [review]

**Comment by nakambo** [comment]
> An FYI, on macOS I get a crash when I try to change anchors with the new button..

Fixing here #2952

**Pull request merged**
