### PR TITLE
Update to React Native 0.66

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [x] win32 (Office)
- [x] windows
- [x] android

### Description of changes

CAUTION: Don't merge until downstream dependencies are updated to RN 0.66 _first_

This change updates the entire repo to React Native 0.66. Because this is a fairly large change, I tried to have each individual commit to be easy-to-read steps. 

Working:
- iOS and macOS test apps boot fine and seem to work

Open issues:
- We use "Picker" from React Native in several places. In RN 0.66, it is removed from Core and must be consumed from the community module. Furthermore, I think Picker just doesn't exist anymore for react-native-win32 so we need to move all usage of that in our repo away.
- Windows crashes on boot. Probably because of the reason above, but we can autolink the community module for windows at least.

### Verification

Ran the iOS and macOS test app. Still need to run Android, Windows, Win32

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by samuelfreiberg** [comment]
I'd like to formulate a testing plan before this gets merged. I'm going to do a gap analysis on what we have in automation testing vs. everything we want to test. With an update this big, I think verification is super important. Perhaps we can sync early next week and discuss and testing plan with the whole team

**Comment by samuelfreiberg** [comment]
And you mentioned: "Don't merge until downstream dependencies are updated to RN 0.66 first". How long do we intend that to take?

**Review by ValentinaKozlova — COMMENTED** [review]
How are we going to replace Picker? I see that there are a lot of suggestions to use `react-native-picker-select`. What do you think? I know we don't want to use a lot of third-party libraries but this one doesn't look bad

**Comment by Saadnajmi** [comment]
Closing in favor of #1809

**Pull request closed without merging**
