### PR TITLE
Fix PR pipeline - remove section containing dead repo link

### PR DESCRIPTION
**Pull request by lyzhan7**
### Platforms Impacted
- [x] iOS
- [x] macOS
- [x] win32 (Office)
- [x] windows
- [x] android

### Description of changes

PR checks are failing due to this dead link (although I'm able to open the link in a browser without any issues)

### Verification

CI passes

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by lyzhan7** [comment]
Pretty sure I should be able to test this locally by running `yarn test-links` but for some reason running that command just hangs. If this isn't the right way to check links locally let me know

**Review by Saadnajmi — APPROVED** [review]
Thanks for the fix!

**Comment by harrieshin** [comment]
that super wierd. are we moving these instructions to owiki orsoemthing?

**Comment by Saadnajmi** [comment]
@harrieshin I think they are no longer relevant (Android emulators should just work on M1 machines). Also the link to apkmirror is.. not something I'd want in our open source repo.

**Pull request merged**
