### PR TITLE
[Testing] Update how appium windows driver gets installed

### PR DESCRIPTION
**Pull request by rurikoaraki**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

(a summary of the changes made, often organized by file)

### Verification

(how the change was tested, including both manual and automated tests)

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Is this still necessary? Asking since we're any to have a brown bag about e2e testing

**Comment by rurikoaraki** [comment]
> Is this still necessary? Asking since we're any to have a brown bag about e2e testing

I mean it'd be nice since it means that the windows driver would use the already downloaded copy of appium-windows-driver instead of downloading a new copy with all its dev dependencies (which we don't need). It's not something that's changing what appium does, just how the driver gets pulled/installed.

**Comment by Saadnajmi** [comment]
Thanks for the clarification! I wasn't sure the original intention, and that makes sense :)

**Comment by rurikoaraki** [comment]
> Thanks for the clarification! I wasn't sure the original intention, and that makes sense :). It's probably also valid for macOS then since we are most likely also installing appium twice

Ah yeah I just noticed that I left everything blank. Probably because I was using this PR to test CI.

**Pull request closed without merging**
