### PR TITLE
Add missing dep

### PR DESCRIPTION
**Pull request by rurikoaraki**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

I don't really know how this has worked til now and idk how our dep checker didn't catch it, but it's keeping me from debugging something in a different repo so... fixing it.

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Comment by rurikoaraki** [comment]
>ERR! [10:32:41 PM] ■ started 'depcheck'
ERR! [10:32:42 PM] x Unused dependencies
ERR! [10:32:42 PM] x -- @fluentui-react-native/memo-cache
ERR! [10:32:42 PM] x Error detected while running 'depcheck'
ERR! [10:32:42 PM] x ------------------------------------
ERR! [10:32:42 PM] x Dependency checking failed
ERR! [10:32:42 PM] x ------------------------------------

Lies!

**Comment by rurikoaraki** [comment]
Idk why but depcheck is just skipping scanning useStyling.ts.

**Comment by rurikoaraki** [comment]
Spent a few hours looking into this but not really worth more than that at the moment. Just going to ignore the message for now.

**Comment by rurikoaraki** [comment]
Logged #1911

**Pull request merged**
