### PR TITLE
Update to React Native 0.71

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

- Bump versions of a bunch of packages to align with 0.71.
- Format of snapshot files changed.
- Various prop type changed to React.PropsWithChildren<propType>
- `/** @jsxRuntime classic */` added to files using `/** @jsx withSlots */`

## Some interesting files to look at:
| File | Notes |
|-----|-----|
| packages/experimental/RadioGroup/src/RadioGroup/RadioGroupExperimental.test.tsx | Made some tests async and added calls to renderer.act to allow react callbacks to call before the jest instance is torn down |
| packages/experimental/Shimmer/src/Shimmer.test.tsx | Made some tests async and added calls to renderer.act to allow react callbacks to call before the jest instance is torn down |
| packages/framework/framework/babel.config.js | babel runtime set to classic  |
| packages/libraries/core/babel.config.js | babel runtime set to classic  |
| packages/theming/apple-theme/src/__tests__/apple-theme.test.ts | Added a mock for AccessibilityInfo to allow  AccessibilityInfo.isHighContrastEnabled call during jest test |
| packages/theming/apple-theme/src/appleColors.macos.ts | suppression of TS error due to types not properly exported from rn-macos [ TODO file a bug / fix in rn-macos] |
| packages/theming/apple-theme/src/createAppleTheme.macos.ts | suppression of TS error due to bad TS types from rn-macos
| packages/utils/adapters/src/adapters.*.ts | Need to look at these files more carefully |
| packages/utils/test-tools/src/enzymeTests.ts | ignoring specific changes that pressable causes, which breaks a bunch of jest tests |

### Verification

(how the change was tested, including both manual and automated tests)

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by rohanprasadofficial** [comment]
Hi @Saadnajmi , Any blockers on this or is this planned for this fork or moved to next fork ?

**Comment by Saadnajmi** [comment]
> Hi @Saadnajmi , Any blockers on this or is this planned for this fork or moved to next fork ?  

Moved to May

**Review by rurikoaraki — APPROVED** [review]

**Review by rurikoaraki — APPROVED** [review]

**Comment by acoates-ms** [comment]
I think I've tracked down the UWP failure.  I think it is due to these changes: https://github.com/microsoft/react-native-windows/pull/10686 / https://github.com/microsoft/react-native-windows/pull/10569.  Looks like RNW is overriding the accessible value if a control is not focusable.  This seems wrong.

**Review by rurikoaraki — APPROVED** [review]

**Review by rurikoaraki — APPROVED** [review]

**Pull request merged**
