### PR TITLE
RadioButton: Fix truncation in RTL mode

### PR DESCRIPTION
**Pull request by chiuam**
### Platforms Impacted
- [ ] iOS
- [X] macOS
- [ ] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes
Two RTL issues on macOS:
  1. RadioButton label gets truncated
  2. Some native controls(RadioButton and Checkbox) are left-aligned

This PR fixes issue 1 by setting the width to fill 100% to its parent view. (Note: Since RadioButton doesn't support multiline, truncation can still happen if the string is wider than its parent view.)
For issue 2, I couldn't figure out the root cause but seems like there's limitation around text alignment as mentioned [here](https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps#limitations-and-future-plan) and [RNTester](https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/js/examples/RTL/RTLExample.js#L671).

Edit: created #2025 as followup

### Verification

(how the change was tested, including both manual and automated tests)

| |  Before                                       | After                                      |
|-----------------------| -----------------------|--------------------------------------------|
|RTL|image | image |
|LTR|image | image |
### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [X] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Review by mischreiber — APPROVED** [review]

**Comment by harrieshin** [comment]
is the radiobutton after screenshot not updated correctly?

**Comment by chiuam** [comment]
> is the radiobutton after screenshot not updated correctly?

I took another look, they seem fine. What do you see wrong?

**Comment by harrieshin** [comment]
> > is the radiobutton after screenshot not updated correctly?
> 
> I took another look, they seem fine. What do you see wrong?

the 3rd row before and after doesn't seem to have any changes?

**Comment by chiuam** [comment]
> > > is the radiobutton after screenshot not updated correctly?
> > 
> > 
> > I took another look, they seem fine. What do you see wrong?
> 
> the 3rd row before and after doesn't seem to have any changes?

Oh I see, the third row is showing there's no visual changes in LTR mode. (updated PR description)

**Pull request merged**
