### PR TITLE
Add "Segoe UI Semibold" font to defaults for semibold variants

### PR DESCRIPTION
**Pull request by ksiler**
### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [x] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

Adds "Segoe UI Semibold" font to defaults for semibold variants. 

Previously, using "Segoe UI" for semibold variants rendered as bold when rich labels were being used. I have a native change that fixes this so this just updates the default fallback values.

### Verification

(how the change was tested, including both manual and automated tests)

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| 
image
 | 
image
 |

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

**Comment by Saadnajmi** [comment]
This might cause problems with the apple platforms. I remember the very first big we ran into for MS Build was along the lines of segoe ui not existing on iOS/macOS

**Comment by ksiler** [comment]
> This might cause problems with the apple platforms. I remember the very first big we ran into for MS Build was along the lines of segoe ui not existing on iOS/macOS

Thanks for bringing this up! Perhaps I should make "Segoe UI Semibold" the secondary font face and it apply it that way so it doesn't effect Apple. I'm not sure if this is the right move though. @tkamireh @FalseLobster do you have any recommendations?   

This is a bit of a special case where the primary font face ("Segoe UI") does not work for rendering semibold text on win32. We currently have "System" set for the other parts of font family (secondary, cursive, monospace, etc.) so we could stick "Segoe UI Semibold" in one of those spots but I'm not sure that's what we want to do. Should this be a question for design?

**Comment by Saadnajmi** [comment]
Also side note, I'm pretty sure this change affects all platforms and not just win32 (looking at change notes). I'm happy to test things on iOS/macOS by pulling in the change! I'm sure not everyone has access to a Mac =)

**Comment by tkamireh** [comment]
@ksiler I'm understanding correctly in that the native fix addresses this and this change is not strictly necessary? If we can specify what we want text to look like without bringing in an additional font face that seems preferable to me.

**Comment by ksiler** [comment]
> @ksiler I'm understanding correctly in that the native fix addresses this and this change is not strictly necessary? If we can specify what we want text to look like without bringing in an additional font face that seems preferable to me.

@tkamireh Yes that's correct. I have a native change that covers this for win32 but thought I would update the defaults (or fallback values) in the event the theming module doesn't load correctly. I'm not sure how often or likely that will happen but if it does, semibold font variants would render as bold on win32. Is that something we're willing to live with to avoid adding additional font faces here? Or should we create a case for win32 like macos and ios?

**Review by tkamireh — APPROVED** [review]

**Review by Saadnajmi — APPROVED** [review]

**Pull request merged**
